POST https://news-web-app.azurewebsites.net/article
Content-Type: application/json

{
    "description": "seventh article",
    "publishdate": "12/24/2023",
    "keyword": "fashion",
    "imgurl": "null"
}